root: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
    - 'import'
    - 'html'
    - 'jest'
    - 'lit-a11y'
    - 'wc'

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:import/errors'
    - 'plugin:import/warnings'
    - 'eslint-config-prettier'
globals:
    page: true
rules:
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/no-non-null-assertion': off
    import/named: off
    import/no-unresolved: off
    import/extensions:
        - error
        - always
        - ignorePackages: true
    import/no-extraneous-dependencies:
        - error
        - devDependencies:
            - "**/*.spec.ts"
            - "src/test-setup/*"
            - "browser-tests/test-setup/*"
env:
    "jest/globals": true
