language: node_js
services: xvfb
node_js:
  - "14"
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
        - yarn build
      workspaces:
        create:
          name: dist-artefact
          paths:
            - dist
    - stage: release
      workspaces:
        use: dist-artefact
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release --branches main
          on:
            branch: main
