language: node_js
node_js:
  - "14"
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: release
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release --branches main
          on:
            branch: main
