name: Jobs
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn --frozen-lockfile
      - run: npx playwright install-deps
      - name: Test
        run: |
          yarn lint
          yarn test
        env:
          CI: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release  --branches main
      - name: Archive screenshot diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
