name: Jobs
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn --frozen-lockfile
      - run: npx playwright install-deps
      - name: Test
        run: |
          yarn lint
          yarn test
        env:
          CI: true
      - name: publish
        run: npx semantic-release --branches main
